title: XLR8 Mastering the CAF Strategy and Planning Phase
description: This workshop is designed to help participants develop a comprehensive cloud adoption strategy and plan for StoreConnect Retail, a growing regional retailer.

# Theme settings - use the standard GitHub Pages theme approach
remote_theme: pmarsceill/just-the-docs

url: https://jonathan-vella.github.io
baseurl: "/xlr8-strategyplan"

# GitHub Pages specific settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

aux_links:
  Template Repository: https://github.com/jonathan-vella/xlr8-strategyplan

# For proper linking in the navigation
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Enable callouts
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
