title: XLR8 Mastering the CAF Strategy and Planning Phase
description: This workshop is designed to help participants develop a comprehensive cloud adoption strategy and plan for StoreConnect Retail, a growing regional retailer.
theme: just-the-docs

url: https://jonathan-vella.github.io

aux_links:
  Template Repository: https://github.com/jonathan-vella/xlr8-strategyplan
